name: Deploy Frontend changes to S3
on:
  push:
    branches:
      - main
env:
  AWS_S3_BUCKET: "cloud-resume-challenge19"
  AWS_REGION: "us-east-1"
  CLOUDFRONT_DISTRIBUTION_ID: "E2R8WPASJY5TY"
  
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure AWS Credentials Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-session-name: admin
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::905418409332:role/github-actions-frontend-role
        
      - name: S3 Upload
        run: |
          aws s3 cp ./resume_website/* s3://${{ env.AWS_S3_BUCKET }}/

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_REGION: ${{ env.AWS_REGION }}

